---
title: "README"
output:
  html_document: default
  pdf_document: default
date: "2024-06-05"
---

{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)


[Github Page](https://github.com/WanheLiLab/)

[Li Lab Page](https://wanheli2022.wixsite.com/wanheli)

Created by Daniel Nguyen, Esther Doria, & Wanhe Li August 2024

Copyright (C) year-range Full Names

Contact: [wli01\@tamu.edu](mailto:wli01@tamu.edu){.email}

## Introduction


Installation

```{Main echo = TRUE}
install.packages("devtools")
library(devtools)
install_github('Wanhelilab/gigem')
library(gigem)
```








## 1. Experiment parameters

### 1.1 Monitor specifications

Your working directory folder should include both the R files, and monitor files together
```{Main echo = TRUE}
DATA_DIR<-dirname(rstudioapi::getSourceEditorContext()$path)
setwd(DATA_DIR)
library(data.table)

# Title for data analysis.
Title="Insert_Name"
```

You can see the variables `file` `monitor`, and `region_id`. `file` refers to the particular files generated by the Drosophila Activity Monitor (DAM), which should give you a chart of 1s and 0s showing when the animal crossed the infrared laser beam. You can change the number of monitors you want to analyze simply by adding or subtracting the .txt file names to the `file` list. The total number of monitors to be analyzed must be reflected in a matching number of entries throughout the rest of the variables from `file` to `treatment`. This means if you analyze two DAM systems, each variable should have exactly two items in the lists.

The term `each = 32` in the variables signifies that each DAM monitor holds 32 flies. If your monitor holds more or fewer flies, you will need to change this number for each of the variables.

```{Main echo = TRUE}

  file = rep(c("Monitor33.txt", "Monitor17.txt",
               "Monitor39.txt","Monitor35.txt",
               "Monitor55.txt", "Monitor57.txt",
               "Monitor13.txt","Monitor52.txt"), each = 32),
  
  # Monitor identifier
  monitor = rep(c("M33","M17",
                  "M39","M35",
                  "M55","M57",
                  "M13","M52"), each = 32 ),
  
  # Unique identifier for each region, same as number for each
  region_id = 1:32,
```         

### 1.2 OK or notOK Status
 
The standard `status` of each fly is "OK". See section 2.2 to manually change the `status` of certain flies and, consequently, omit them from analysis

```{Main echo = TRUE}
  # Status of the data (e.g., "OK")
  status = "OK",
```

### 1.3 Start/stop points

The `start_datetime` should be the first light-on time-point (as registered by the monitoring computer) after the flies have been loaded into the monitor(s). The `stop_datetime` is the last light-on time-point (plus a few minutes) before removing them from the monitors. Typically, this will be between two to four Zeitgeber cycles (48-96 hours for a typical 24-hour cycle) from the `start_datetime` time-point. Please ensure that the time `stop_datetime` is a few minutes past the light-on time point; this will ensure none of the functions which deal with time are hindered.

```{Main echo = TRUE} 
# Start datetime for monitoring period
  start_datetime = "2019-06-22 10:05:00",
  
  # Stop datetime for monitoring period
  stop_datetime = "2019-06-24 10:20:00",

```         

### 1.4 Organism specifications

Match the temperature, sex, genotype, and stock number of the flies to their respective monitors as listed above. For example, 

`file` = `Monitor33.txt` correlates to `monitor` = `M33`, `temp` = `21.5C`, `sex` = `M` (for male), `genotype` = `CS`, `BDSC` = `CS,` and `treatment` = `Iso_2D`. 

```{Main echo = TRUE}
  # temperature during monitoring
  temp = rep(c("21.5C", "21.5C",
               "21.5C", "21.5C",
               "21.5C", "21.5C",
               "21.5C", "21.5C"), each = 32),

 # Sex of the subject being monitored
  sex = rep(c("M","M",
              "M","M",
              "M","M",
              "M","M"), each = 32),
  
  # all genotypes of the subject being monitored
  genotype = rep(c("CS", "CS", 
                   "SIP-L2-3", "SIP-L2-3",
                   "SIP-L2-4", "SIP-L2-4", 
                   "SIP-L2-5", "SIP-L2-5"), each = 32),
  
  # Bloomington Drosophila Stock Code associated with the subject being monitored
  BDSC = rep(c("CS", "CS", 
               "76293", "76293",
               "76294", "76294", 
               "76295", "76295"), each = 32),
```

### 1.5 Experimental treatments

This is where you would specify any experimental treatments for each population such as social isolation, change in diet, sexual deprivation, etc., following the same order as the previous variables.

```{Main echo = TRUE}
# Treatment applied during monitoring period
  treatment = rep(c("Iso_2D","Grp_2D",
                    "Iso_2D","Grp_2D",
                    "Iso_2D","Grp_2D",
                    "Iso_2D","Grp_2D"),each = 32)
```         

## 2. Data Trimming and Summarizing

### 2.1 Package Dependencies

Download and load all packages required.

```{Main echo = TRUE}
required_packages <- c("damr", "ggetho", "sleepr", "data.table", "zeallot", "plyr")

# Install and load required packages
for (pkg in required_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
  }
  library(pkg, character.only = TRUE)
}
```

### 2.2 Removing animals from analysis

If you need to remove animal from analysis -say you find mold in one of the cuvettes-, you can run setStatus; repeat as necessary for different regionID and monitor combinations.

```{Main echo = TRUE}
# change status manually for cuvettes to exclude from analysis,
# provide RegionID and Montior, repeat as necessary.
info <- setStatus(info, regionID=4, monitor="M33")

# remove rows whose status is not "OK"
info <- info[status != "notOK"]
```

### 2.3 Store experiment parameters

Create an object of class `ExperimentData` -which is defined in `Functions.R`-, and populate it's variables with the experiment parameters provided above.

```{Main echo = TRUE}
# Create an object, that contains all of your inputs
experimentDataObject <- new("ExperimentData", 
                            Batch = Title, 
                            monitorlist = as.list(unique(info$monitor)), 
                            genotypelist = as.list(unique(info$genotype)), 
                            loadinginfo = info)
```

### 2.4 Store meta data

We create a meta data object, that separates metadata from the data we're conducting computations on for efficiency. We provide the created function `writeLoading` with the info stored in our object

```{Main echo = TRUE}
# store this as a csv file, used to curate summary tables
loading_metadata <- writeLoading(experimentDataObject)
```

### 2.5 Activity and Sleep plots 

After metadata is created, we're ready to make activity and sleep plots for each
monitor. PDFs will be generated in the current working directory and named
`[Title]_sleep_by_monitor[MX].pdf` and `[Title]_activity_by_monitor[MX].pdf`
This will also create a temporary data table called `dt_activity` which will
continue to be transformed by subsequent functions.

```{Main echo = TRUE}
#create activity plots and sleep plots of each monitor at t times
dt_activity <- activityAndSleep(experimentDataObject, loading_metadata)
```

### 2.6 Dead animal removal

We want to trim off any animals that have died before the end of the experiment.
Within the function `aliveVsDead`, we first use the `curate_dead_animals` function by `sleepr` to automatically detect and remove
animals with very long bouts of immobility.
`removed_list1_[Title].csv` is written, containing the IDs of animals removed, and the plots `[Title]_sleep_before_deadcheck.pdf `and `[Title]_sleep_after_deadcheck.pdf`
are made depicting the sleep profiles before and after removal of dead animals.

```{Main echo = TRUE}
#create activity plots before and after removing "dead" #provides list of IDs removed from first trimming 
dt_curated <- aliveVsDead(experimentDataObject, dt_activity)
```

Despite automatic removal, we want to ensure we've captured all dead animals.
We then remove all animals whose detected lifespan does not extend to the end of
the experiment. We create a second csv, `removed_list2_[Title].csv`, for these removed
animals. We also create the plots `[Title]_population_sleep.pdf` and `[Title]_population_sleep_wrap.pdf` for the percentage of the population asleep: 1) during the first 48-hours and 2) averaged based on time-points to show the mean 24-hour cycle.

```{Main echo = TRUE}
#further removal and trimming of animals that died before specified time 
#provides list of IDs removed from second trimming 
dt_final <- manualDeadRemoval(experimentDataObject, dt_curated, num_days=2)
```

### 2.7 Sleep Time, Fraction & Bout Lengths

Finally, we create a CSV `summary_[Title].csv` that summarizes the experiment data,
we calculate day/night phase for time points, and the sleep fraction and sleep time 
for all, day, and night phases for each id, including 4-hour bins for ZT0-4.
Bout values are calculated, and statistics summary generated, and plotted as `[Title]_population_sleep_bout_wrap.pdf`.

```{Main echo = TRUE}
#write bout length pdf, and calculate bout and latency stats. 
# generates data for groups sleep_time_all, sleep_time_l, sleep_time_d, sleep_time_ZT0_4 
dt_finalSummary <- clean_summary(experimentDataObject, dt_final, num_days=2, loading_metadata)
```

## 3. Generate Statistical Summaries 
### 3.1 Inputs

Sleep time and bout information was compiled and will be
used for for generating statistical summaries.

```{Main echo = TRUE}
# input column names that you want normalized statistics for:
groups <- c("sleep_time_all", "sleep_time_l", "sleep_time_d", "sleep_time_ZT0_4",
            "sleep_time_ZT18_24", "n_bouts_L","mean_bout_length_L","n_bouts_D","mean_bout_length_D") 
norm_factor <-dt_finalSummary[,lapply(.SD,mean), by = .(genotype,treatment), .SDcols = groups]
```

### 3.2 Summary of Statistics

So far, we have the experiment parameters, the summary table generated from `clean_summary`,
and the column names in `groups`. This information is generates a table summarizing
mean, standard deviation, standard error, and confidence intervals (default 0.95) and saves as `stat_[Title].csv`

```{Main echo = TRUE}
#summary of statistics of sleep time for all groups 
stat_summary <- statsSummary(experimentDataObject, dt_finalSummary, groups)
```

### 3.3 Statistics of normalized data

We generate a table of normalized values -`norm_summary_[Title].csv`- and calculate statistics for these values -`stat_norm_[Title].csv`.

```{Main echo = TRUE}
#calculates normalized statistics of sleep time for all groups 
norm_summary <- normSummary(experimentDataObject, dt_finalSummary, groups, norm_factor)
```

### 3.4 Statistics of normalized data for specified genotype

We can generate normalized statistics for a specific genotype listed from the initial experiment parameters. Because "CS" is our control genotype, we provide `geno` with `"CS"` which outputs `norm[geno]_summary_[Title].csv` and `stat_norm[geno]_summary_[Title].csv`

```{Main echo = TRUE}
#calculates normalized statistics of sleep time for your specified genotype 
CS_norm_summary <- CS_normSummary(experimentDataObject, dt_finalSummary, groups, norm_factor, geno="CS")
```

### 3.5 Population Sleep Plots for genotypes

PNG plots are created for each different genotype showing population sleep in percentage. These save as
`[Genotype]_[Title]_population_sleep_wrap.png

```{Main echo = TRUE}
#generate PNGs for sleep_wrap data for genotypes 
png_genotypes(experimentDataObject, dt_final)
```
