---
title: "README"
output:
  html_document: default
  pdf_document: default
date: "2024-12-02"
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


[Github Page](https://github.com/WanheLiLab/gigem)

[Li Lab Page](https://wanheli2022.wixsite.com/wanheli)

Created by Esther Doria, Wanhe Li, & Daniel Nguyen August 2024

Copyright (C) year-range Full Names

Contact: [estheridoria\@gmail.com](mailto:estheridoria@gmail.com){.email}

## Installation

Install and attach devtools which can install gigem
```{Main echo = TRUE}
install.packages("devtools")
library(devtools)
```

Install and attach gigem
```{Main echo = TRUE}
install_github('Wanhelilab/gigem')
library(gigem)
```

Install the example data to use as a template (or copy the information from this file into a new script).
```{Main echo = TRUE}

```


## 1. Experimental parameters: Creating a 'Main.R' file

Each sub-directory folder should be named 'Batch' followed by any combination of letters, numbers and/or underscores, effectively labeling the experiment you ran. Create a main file within each sub-directory, naming it 'Main' followed by the same experimental label used for the sub-directory folder. Add the corresponding monitor.txt files to each sub-directory folder.

### 1.1 Monitor specifications

Within each Main file, name the `Title` the same as the sub-directory folder it is in.

```{Main echo = TRUE}
# Title for data analysis.
Title="Batch..."
```

The variable `file` refers to the particular files generated by the Drosophila Activity Monitor (DAM) System (these should be full of 1s and 0s). Add the names of the monitor files generated in *your* experiment to replace the example ones below. 

```{Main echo = TRUE}
info <- data.table::data.table(
  
  # Filename associated with each monitor data
  file = rep(c("Monitor33.txt", "Monitor17.txt",
               "Monitor39.txt","Monitor35.txt",
               "Monitor55.txt", "Monitor57.txt",
               "Monitor13.txt","Monitor52.txt"), each = 32),
```

Add the corresponding monitor numbers to the `monitor` variable in the same order, preceded by 'M'. 

```{Main echo = TRUE}
    
  # Monitor identifier
  monitor = rep(c("M33","M17",
                  "M39","M35",
                  "M55","M57",
                  "M13","M52"), each = 32 ),
```

Throughout this file, both `region_id` and the term `each = 32` signifies the number of flies each DAM monitor holds. If your monitor holds more or fewer flies than 32, you will need to change this number for each of the variables.

```{Main echo = TRUE}
  # Unique numerical identifier for each arena within the DAM
  region_id = 1:32,
```         

### 1.2 OK or notOK Status
 
The standard `status` of each fly is "OK". See section 1.6 to manually change the `status` of certain flies and, consequently, omit them from analysis

```{Main echo = TRUE}
  # Status of the data (e.g., "OK")
  status = "OK",
```

### 1.3 Start/stop points

The `start_datetime` should be the first light-on time-point after the flies have been loaded into the monitor(s). The `stop_datetime` is the last light-on time-point (plus a few minutes) before removing them from the monitors (or when your experiment is scheduled to end). Typically, this will be between two to four Zeitgeber cycles (48-96 hours for a typical 24-hour cycle) from the `start_datetime` time-point. Please ensure that the time `stop_datetime` is a few minutes past the light-on time point; this will ensure none of the functions that deal with time are hindered.

```{Main echo = TRUE} 
# Start datetime for monitoring period
  start_datetime = "2019-06-22 10:05:00",
  
  # Stop datetime for monitoring period
  stop_datetime = "2019-06-24 10:20:00",

```         

### 1.4 Organism specifications

Match the `sex` and `genotype` of the flies to their respective monitors as listed above. For example, 

`file` = `Monitor33.txt` correlates to `monitor` = `M33`, `temp` = `21.5C`, `sex` = `M` (for male), `genotype` = `CS` and `treatment` = `Iso_2D`, `environment` = `"NA"`, `light` = `"12.12"` 

Therefore, the number of entries in each variable should be the same (excepting the ones where each monitor has the same variable attribute, as formatted in `start_datetime` or `sex`)

```{Main echo = TRUE}

 # Sex 
  sex = "M"
  
  # Genotypes
  genotype = rep(c("CS", "CS", 
                   "SIP-L2-3", "SIP-L2-3",
                   "SIP-L2-4", "SIP-L2-4", 
                   "SIP-L2-5", "SIP-L2-5"), each = 32),
  
```

### 1.5 Experimental treatments

Specify any experimental treatments for each population such as social isolation, change in diet, sexual deprivation, etc..

```{Main echo = TRUE}
  # Temperature during monitoring
  temp = "21.5C"

# Treatment applied during monitoring period
  treatment = rep(c("Iso_2D","Grp_2D",
                    "Iso_2D","Grp_2D",
                    "Iso_2D","Grp_2D",
                    "Iso_2D","Grp_2D"),each = 32),

# Environmental factors
  environment = "NA",
  
# Light.Dark phases
  light = "12.12"
)
...
```         

### 1.6 Manually Excluding notOK flies.

Within certain cuvettes, you may see some factors that would interfere with your experimental results (ex. mold growth, or the incorrect sex). To remove this fly from analysis, change the following code to set the `monitor` equal to `'M'` followed by the monitor number of the compromised fly. Set the `regionID` equal to the arena number in that monitor that the fly inhabited during analysis. Finally, remove the '#' from before `info.` Repeat this process as necessary, adding a new line of code each time.

```{Main echo = TRUE}
# Change status manually to exclude cuvettes from analysis,
# info <- SetStatus(info, regionID=4, monitor="M33")
...
```      

## 2. Running the package: Creating a HitRun.r file 

